### ISSUE TITLE
Compile to ES6 modules

### ISSUE THREAD

**Issue by tkers** [ams-hackers/delisp#39]

**Comment by davazp** [comment]
For this, we can use the same strategy as we did for the user definitions:

https://github.com/ams-hackers/delisp/blob/9aea8e316bb55420d20586762b40029752ccb429/packages/delisp-core/src/compiler/definitions.ts

Implement an interface about how to handle exports and add the specific instance to the environment:
https://github.com/ams-hackers/delisp/blob/9aea8e316bb55420d20586762b40029752ccb429/packages/delisp-core/src/compiler.ts#L44

**Comment by davazp** [comment]
@tkers can we close this one?

**Comment by tkers** [comment]
Just pushed an update so the runtime is also imported properly when using the ESM backend. There are some further improvements that can be built on top of this, but let's close this for now indeed 👍
